# Generated by Django 4.2.2 on 2023-07-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phoneno',
        ),
    ]
