# Generated by Django 4.2.2 on 2023-07-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_phone_employee_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
