# Generated by Django 4.2.2 on 2023-07-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_rename_phoneno_employee_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
